### ISSUE TITLE
Peaks Files

### ISSUE THREAD

**Issue by ngcrawford** [bmvdgeijn/WASP#15]
Quick question: Where do the peaks files come from? See [this line][1] in the workflow example. I think I must have missed a step along the way... 

[1]: https://github.com/bmvdgeijn/WASP/blob/master/workflow.sh#L66

**Comment by gmcvicker** [comment]
The peaks file is currently supposed to be provided by the user. It's provides a list of regions to be tested (e.g. exons or ChIP-seq peaks) and corresponding test SNPs. We need to document this better, and we're also hoping to provide a script that can be used to generate this file for ChIP-seq peaks or transcripts.

**Comment by gmcvicker** [comment]
Hi Nick, we've improved the documentation on how to make the file, and we also added a script that can be used to generate one. This is described here:
https://github.com/bmvdgeijn/WASP/tree/master/CHT#step-5

The script we provide should be able to generate a reasonable set of peaks and test SNPs, but if you have a specific set of SNPs and regions (e.g. peaks or genes) that you want to test you may need to write something custom...

Hope this helps.
