### ISSUE TITLE
Reads with soft clipping

### ISSUE THREAD

**Issue by dgorkin** [bmvdgeijn/WASP#2]
Hi,

Thank you for making this great software available! I encountered what appears to be an issue with handling soft clipped reads that I wanted to bring to your attention. Below is an example of a read that causes this issue. Note that the cigar string is 23S77M. It is these type of reads, where the alignment begins with a soft clip, which seem be the problem.

HWI-ST1113:347:H99VNADXX:1:1207:16477:32946	4	chr10	75531	0	23S77M	*	0	0	AAATGTGTAGCAGTAGGAAAGCTCCCTTGAGAACTGGCACAAGACAAGGATGGCCTCTCTCACCACTCCTATTCAACGTAGTACTGGAATTTCTGGCCAG	CCCFFBDDHHHHHGHIJIIJJJJJJJJJJIJJJIJJJJJJIJEIIJJJJJJJJJJJJIJJJIJJJJJJJJHHHHHHFFEFD?CEEEDDDDDDDECCCDDD	NM:i:0	MD:Z:77	AS:i:77	XS:i:77	

The SNP involved here is: 75552	C	A
It is on chromosome 10 (in the file “chr10.snps.txt.gz”)

find_intersecting_snps.py correctly identifies this read as overlapping the SNP, and writes it  *.to.remap.bam. However, in *.remap.fq.gz, the wrong position is flipped. Here’s the corresponding line in *.remap.fq.gz:

@9:chr10:75530:1
AAATGTGTAGCAGTAGGAAAGATCCCTTGAGAACTGGCACAAGACAAGGATGGCCTCTCTCACCACTCCTATTCAACGTAGTACTGGAATTTCTGGCCAG
+9:chr10:75530:1
CCCFFBDDHHHHHGHIJIIJJJJJJJJJJIJJJIJJJJJJIJEIIJJJJJJJJJJJJIJJJIJJJJJJJJHHHHHHFFEFD?CEEEDDDDDDDECCCDDD

Comparing the original read to the flipped read we can see the flipped position (in brakets []):
AAATGTGTAGCAGTAGGAAAG[C]TCCCTTGAGAACTGGCACAAGACAAGGATGGCCTCTCTCACCACTCCTATTCAACGTAGTACTGGAATTTCTGGCCAG AAATGTGTAGCAGTAGGAAAG[A]TCCCTTGAGAACTGGCACAAGACAAGGATGGCCTCTCTCACCACTCCTATTCAACGTAGTACTGGAATTTCTGGCCAG

However, the SNP, and thus the position that should have been flipped, is actually here (in squiggly brackets {}):
AAATGTGTAGCAGTAGGAAAG[C]TCCCTTGAGAACTGGCACAAGA{C}AAGGATGGCCTCTCTCACCACTCCTATTCAACGTAGTACTGGAATTTCTGGCCAG AAATGTGTAGCAGTAGGAAAG[A]TCCCTTGAGAACTGGCACAAGA{C}AAGGATGGCCTCTCTCACCACTCCTATTCAACGTAGTACTGGAATTTCTGGCCAG

The flipped position is 22 bp from the start of the read.  Notably, the SNP (and position that should have been flipped) is 22 bp from the start of the matched (i.e.“M”) portion of the read.  The first 23 positions in the read are soft clipped (23S77M), and thus the SNP is actually 22+23 = 45 bp from the start of the read. It seems that the problem is: to arrive at the correct SNP position, the distance should be counted from start of the M portion of the read, whereas the script seems to count from the absolute beginning of the read. 

It does seems that the script is designed to handle soft clipped reads, as line 313 is:
if cigar[0] in (0,4): #if CIGAR indicates a match alignment to the reference genome or a soft clipping

 Any insights would be greatly appreciated. 

Thank you!

Best,

Dave

**Comment by dgorkin** [comment]
It seems like replacing line 302: "if cigar[0] in (0,4): #if CIGAR indicates a match alignment to the reference genome or a soft clipping"
...with:
"
if cigar[0] == 4:                   
	p=p+cigar[1]               
        elif cigar[0] == 0:                  
"
...eliminates this issue.

**Comment by bmvdgeijn** [comment]
Hi Dave,

Thanks for pointing out this issue. It appears that the problem is that the
first base that isn't soft-clipped is reported rather that the first base
of the read.  I think that your fix is correct then. I will double check
that all mappers handle soft-clipping this way and make the change.  Let me
know if you run into any more issues.

Best,
Bryce
