### ISSUE TITLE
Correctly re-aligned read pair not included in final mapping output

### ISSUE THREAD

**Issue by cdeboever3** [bmvdgeijn/WASP#23]
I've found a read pair that is re-aligned correctly (and reported as such by WASP) yet is not printed to the final output file. I've included files and code necessary to reproduce the bug here: https://dl.dropboxusercontent.com/u/3886457/wasp_bug.tar.gz. I'm using the most recent code from master. See run.sh for the commands and run.outerr has stdout/stderr.

**Comment by gmcvicker** [comment]
Hi Chris, thanks for this bug report. I'll look into it tomorrow. Sorry about these problems. We're working on putting together a better test pipeline for paired-end reads (we've done most of our development and testing with single-end reads so far).

**Comment by cdeboever3** [comment]
No problem Graham. Would it be useful to refactor and add some unit tests for the mapping scripts? I might have some time to do that.

**Comment by gmcvicker** [comment]
Yes definitely. If you have the time that would be great.

**Comment by cdeboever3** [comment]
I don't know if #25 fixed this problem or not. I haven't had a chance to work on `filter_remapped_reads.py` yet. I'll refactor that next and look into this problem.

**Comment by gmcvicker** [comment]
Oh ok. I will re-open this issue then.

**Comment by gmcvicker** [comment]
I believe / hope that any remaining paired-end read filtering issues have been fixed with release v0.2
