### ISSUE TITLE
StopIteration exception in filter_remapped_read.py

### ISSUE THREAD

**Issue by noahrose** [bmvdgeijn/WASP#30]
Hi there,

For some reason, I'm getting a StopIteration exception at line 137 of filter_remapped_read.py. The iterator is reaching the end of the file without the script expecting it (I checked and the last read really is reached). If I handle the exception and set end_of_file to true (like appears in lots of other places in the script), then the code works fine (I think--at least it outputs results that seem reasonable). Is there any reason that the exception wasn't handled in this case (and I've done something wrong or my files are off...), or is this just a case that didn't come up in testing maybe? Thanks so much for any help, traceback is pasted below!

Traceback (most recent call last):
  File "/home/noahrose/bin/WASP/mapping/filter_remapped_reads.py", line 182, in <module>
    main()
  File "/home/noahrose/bin/WASP/mapping/filter_remapped_reads.py", line 179, in main
    options.orig_num_file, options.is_paired_end)
  File "/home/noahrose/bin/WASP/mapping/filter_remapped_reads.py", line 137, in run
    orig_read = to_remap_bam.next()
  File "pysam/calignmentfile.pyx", line 1561, in pysam.calignmentfile.AlignmentFile.__next__ (pysam/calignmentfile.c:16453)
StopIteration

**Comment by bmvdgeijn** [comment]
Hi Noah,

Thank you for pointing this out.  I think you are right and that this was a
bung that was introduced during some clean up a few weeks ago.  Someone
else emailed with the same issue and I think it has been resolved.  Have
you done a pull request recently (in the last 2 or 3 weeks)?  If not, try
getting the most recent version and it should be resolved.  Otherwise I
will look into it further.

Best wishes!
Bryce

**Comment by noahrose** [comment]
Hi Bryce,

Thanks for responding so quickly! I just re-pulled today, so I wonder if maybe some signals got crossed in gitworld? I'll double check!

Noah

**Comment by noahrose** [comment]
I just double checked and the missing exception still seems to be missing at line 137. Thanks for all of your help!

Noah

**Comment by cdeboever3** [comment]
Are you working with single or paired end data? I've run through a couple hundred samples without problem but it's all been paired end. I haven't tested as extensively for single end.

**Comment by noahrose** [comment]
Yep, that must be it, I'm working with single end.

**Comment by cdeboever3** [comment]
I'll try running some single end data tomorrow and see if I can recreate the bug and fix it to make sure it isn't a deeper problem, but I'm guessing it's fine as you suggested since you're getting to the end of the file.

**Comment by antozito** [comment]
Hi @noahrose  , which version of filter_remapped_reads.py are you using ? Do you know if there are new releases? I implemented but It is so slow that I have to interrupt it (15 hours or more for 1 sample) withou producing results.
Hoping for help..
