### ISSUE TITLE
Recursion failure in Denovo transcriptome

### ISSUE THREAD

**Issue by noahrose** [bmvdgeijn/WASP#31]
I'm attempting to account for mapping biases in a denovo transcriptome, so I'm working across ~20,000 contigs instead of a small number of chromosomes, and I'm reaching the python recursion limit when I point find_intersecting_snps.py to a SNP directory with 20,000 different files. I guess I could split these into sets of 1000 and check each, but is there any way that you can think of to get around this limit, or any possibility of an iterative rather than recursive implementation that might make things more feasible for non-model applications? Thanks so much for any advice!

**Comment by bmvdgeijn** [comment]
I don't see why have fewer or more files should cause a recursion error as
the contigs should be considered one at a time.  Can you send me the error
and I will take a look?

Thanks,
Bryce

**Comment by noahrose** [comment]
Here's the error, there's a whole bunch more repeats of the first line before it:  

File "/home/noahrose/bin/WASP/mapping/find_intersecting_snps.py", line 302, in fill_table
    self.fill_table()
  File "/home/noahrose/bin/WASP/mapping/find_intersecting_snps.py", line 302, in fill_table
    self.fill_table()
  File "/home/noahrose/bin/WASP/mapping/find_intersecting_snps.py", line 275, in fill_table
    self.init_snp_table()
  File "/home/noahrose/bin/WASP/mapping/find_intersecting_snps.py", line 353, in init_snp_table
    self.get_next_snp()
  File "/home/noahrose/bin/WASP/mapping/find_intersecting_snps.py", line 398, in get_next_snp
    self.cur_snp = SNP(snp_line)
  File "/home/noahrose/bin/WASP/mapping/find_intersecting_snps.py", line 40, in __init__
    self.pos = int(snp_split[0]) - 1
RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by bmvdgeijn** [comment]
Ah I see.  It does go a layer deeper every time it goes to a new file with
the init_table().  I will try to come up with a fix.

**Comment by noahrose** [comment]
For other people working with non-model organisms/de novo stuff, a quick work around in the meantime is to put this code at the top find_intersecting_snps.oy:

resource.setrlimit(resource.RLIMIT_STACK,(2**29,-1))
sys.setrecursionlimit(20000)

This increases the maximum recursion limit and stack size that python can use. Not a permanent solution, but it's working for me.

**Comment by gmcvicker** [comment]
I think that any recursion depth issues should now be handled gracefully by --max_snps and/or --max_seqs arguments to find_intersecting_snps.py. In addition it is now possible to limit the number of reads generated (and recursion depth) by only using haplotypes that are present in the samples (rather than all allelic combinations).
