### ISSUE TITLE
Step 3: Remapping Issue with remap.fq.gz files using GEM

### ISSUE THREAD

**Issue by Jia21** [bmvdgeijn/WASP#32]
Hi ,
I used remap.fq1.gz files and used remap.fa2.gz to do step 3. However, it seemed that the fq.gz was not correct. The error information was following:

Second pair input file found: reads_2.fastq.gz

ERROR: Failed to initialize neccessary parameters:

Unable to get pairing information from input.
Please check your read id's and make sure its either in casava >= 1.8 format or the
ids end with /1 and /2

Can you give me some suggestion? 
Thanks.

**Comment by gmcvicker** [comment]
Hi Jia,

We have not tried using the GEM mapper with WASP yet. Can you provide us with the command line arguments that you are providing to GEM and we will see if we can solve your problem?

**Comment by Jia21** [comment]
Hi,

Very thanks for considering my question. It now seems to be solved. 
But I just want to extract the reference counts and the alternative allele counts for heterozygous SNP sites. Can I obtain them through WASP or can you tell me which command lines should I use? Thanks.

Regards
Jia
——————————————————
Jia Wen, Ph.D., Postdoc research
Department of Bioinformatics and Genomics
College of Computing and Informatics
University of North Carolina at Charlotte
9201 University City Blvd., Charlotte, NC 28223
Phone: 704-687-5014
Email: jwen6@uncc.edu <mailto:jwen6@uncc.edu>

**Comment by gmcvicker** [comment]
Hi Jia,
Steps 1-4 of the CHT workflow (https://github.com/bmvdgeijn/WASP/tree/master/CHT) create binary HDF5 files that contain counts of reads that match reference and alternative alleles at all heterozygous sites. These files can be read using PyTables or Pandas or other tools for reading HDF5 files. Alternatively you can follow Step 5 to write the counts to a BED-like text file, however this file contains a lot of other information as well. If these files do not work for you, please let us know. I have some code that, with a bit of effort, could be modified to convert HDF5 files to wig files.

**Comment by Jia21** [comment]
Hi,

Thanks very much. 
I will try this step. 
1. But before that I am confusing on step 4 of mapping workflow, what does '<output.bam> file where reads that are kept after remapping are stored’ mean? Do you mean the output.bam is the output bam file result in step 4, and can  I name it randomly?
2. And at the step 5 of mapping workflow, you said that 'At the end of the pipeline, ${LANE_NAME}.keep.bam and ${LANE_NAME}.remap.keep.bam can be merged for a complete set of mappability filtered aligned reads’. I just used smalls merge command line to merge the ‘.keep.bam’ file from step 2 and ‘.remap.keep.bam' from step 4. Am I right?
Thanks.

Regards
Jia
——————————————————
Jia Wen, Ph.D., Postdoc research
Department of Bioinformatics and Genomics
College of Computing and Informatics
University of North Carolina at Charlotte
9201 University City Blvd., Charlotte, NC 28223
Phone: 704-687-5014
Email: jwen6@uncc.edu <mailto:jwen6@uncc.edu>
