### ISSUE TITLE
filter_remapped_reads.py. very slow?

### ISSUE THREAD

**Issue by antozito** [bmvdgeijn/WASP#33]
Dear owner, 
I am implementing wasp mappability filter pipeline in order to improve the mapping. Every thing OK, 
however, when running filter_remapped_reads.py it is very slow (more than 10 hours without results, output.bam empty and so I stop it because it is still running.).  Possible so slow just for one sample? I do not think so. Here the message I get after stopping the algorithm,

Traceback (most recent call last):
  File "filter_remapped_reads.py", line 180, in <module>
    main()
  File "filter_remapped_reads.py", line 177, in main
    options.orig_num_file, options.is_paired_end)
  File "filter_remapped_reads.py", line 48, in run
    chrm = remap_read.qname.strip().split(":")[1]
KeyboardInterrupt

What the problem is? 
Are there new versions of the script that fix the problem ?

many thank for help
antonino
King's College London

**Comment by bmvdgeijn** [comment]
Hi Antonino,

That step of the script shouldn't take very long.  Have you done a pull
recently?  If not try that.  How many reads you mapping?

**Comment by antozito** [comment]
Dear owner, I fixed the problem. The problem involved the indentation of python code..
I fixed compared with that provided in this site easily in emacs.
Thank you...good software I think..
I am implementing..

antonino
