### ISSUE TITLE
ImportError: No module named libchtslib

### ISSUE THREAD

**Issue by antozito** [bmvdgeijn/WASP#36]
Dear owner, 

I implemented WASP im my computer various time, and it performs very well, good algorithm.
However, when I run  find_intersecting_snps.py (In WASP mappability filter) my account in a server
a get this error:

-----------
Traceback (most recent call last):
  File "find_intersecting_snps.py", line 6, in <module>
    import pysam
  File "/gpfs/home/zitoa/ChrX/apps/WASP/pysam/__init__.py", line 1, in <module>
    from pysam.libchtslib import *
ImportError: No module named libchtslib
---------------

Why ?? I did not find this module in the pysam folder.

Best, 
anto

**Comment by antozito** [comment]
@bmvdgeijn 
Dear owner,

I implemented WASP im my computer various time, and it performs very well, good algorithm.
However, when I run find_intersecting_snps.py (In WASP mappability filter) my account in a server
a get this error:

Traceback (most recent call last):
File "find_intersecting_snps.py", line 6, in
import pysam
File "/gpfs/home/zitoa/ChrX/apps/WASP/pysam/init.py", line 1, in
from pysam.libchtslib import *

Why ?? I did not find this module in the pysam folder.

Best,
anto

**Comment by gmcvicker** [comment]
Hi Anto,
The error is coming from pysam, which is a wrapper around the htslib C library. The error message indicates that it is unable to import the module that wraps the C library. I suspect that the error indicates that pysam was either not compiled or installed correctly. Please try to re-build and/or re-install pysam.

Graham

**Comment by antozito** [comment]
@gmcvicker 

many thanks, 

best 
anto
