### ISSUE TITLE
Calibrating CHT using permutation

### ISSUE THREAD

**Issue by boxiangliu** [bmvdgeijn/WASP#37]
Hello Bryce and Graham,

I would like to calibrate CHT on my dataset using permutation. In the paper supplement you mentioned that you permuted total read depths (and matching genome-wide read depth counts) and randomly flipped allele-specific counts at linked heterozygous SNPs with probability 0.5. I wonder if this can be accomplished by simply flipping the genotypes at every SNP with probability 0.5 in the VCF file? If not, what is the concern and how did you flip the counts? Thank you and happy holidays!

**Comment by gmcvicker** [comment]
Hi Bosh,
The goal of the permutation is to keep the total read counts and allele specific read counts the same but break the association with genotype. I think that randomly swapping genotypes (between individuals) at every SNP in the VCF would accomplish much the same thing.

In any case, the permutation approach that we use is implemented in the combined_test.py script. You should be able to permute the data by running the combined_test.py script with the --shuffle flag.

Hope this helps,

Graham

**Comment by boxiangliu** [comment]
Thank you very much Graham! This help a lot.
