### ISSUE TITLE
Intersecting SNPs

### ISSUE THREAD

**Issue by narayananr** [bmvdgeijn/WASP#40]
Hi

I am seeing lot of warnings that says "SNP out of order has been skipped" while using "find_intersecting_snps.py". Can you please explain what the warning means and is it okay to ignore?

Thank you

**Comment by cdeboever3** [comment]
What do your SNP files look like? Are they sorted by position?

**Comment by narayananr** [comment]
They were sorted by position. The problem went away when SNP positions do not contain "reference skips" regions.
