### ISSUE TITLE
filter_remapped_reads single end pulls two reads at atime

### ISSUE THREAD

**Issue by noahrose** [bmvdgeijn/WASP#41]
Hi there,

I noticed that as currently written, filter_remapped_reads.py pulls a second read in each loop of the read filter, as if it is in paired end mode.

            #else:
            #    try:
            #        second_read = to_remap_bam.next()
            #        print "what?"
            #    except:
            #        end_of_file=True
            #        break

This bit of code actually seems to be redundant to the lines just above it as far as I can tell?

                if is_paired_end:
                    try:
                        orig_read = to_remap_bam.next()
                    except:
                        sys.stderr.write("File ended unexpectedly (no pair found).")
                        exit()
                    keep_bam.write(orig_read)

If I comment those lines out, the script seems to work as intended on (single end) test data. Let me know if I'm misunderstanding something about the purpose of that code. I pulled freshly today, so I don't think it's an old problem. Cheers!

Noah

**Comment by noahrose** [comment]
oops sorry I meant to say the code in question is on lines 131-138

**Comment by bmvdgeijn** [comment]
Hi Noah,

I am in the process of moving from Chicago to Boston, but I will check this out as soon as I can.

Thanks,
Bryce

**Comment by noahrose** [comment]
Looking over the code some more, I think I was wrong in thinking that code is redundant (I think it's burning through the second read in a pair if we decide not to keep the first read on the basis of it not mapping correctly?), just that the conditional should probably read
"elif paired_end:"
instead of 
"else:"
since we only want to burn through a second read if we are dealing with paired end data.

Sorry for my probable misreading before, let me know if you think that is correct or if I have things mixed up.

**Comment by gmcvicker** [comment]
I think that the original code was correct, but in any case, this part of the code has now been completely re-written, so closing this issue.
