### ISSUE TITLE
find_intersecting_snp get stuck

### ISSUE THREAD

**Issue by boxiangliu** [bmvdgeijn/WASP#42]
Hi Bryce and Graham,

I am running find_intersecting_snp.py to filter a mouse RNAseq dataset mapped onto the GRCm38 reference genome. However, the script somehow got stuck at chromosome 17. More specifically, it has not been printing reads to *.to.remap.bam for the past 24 hours. I ran the job twice and the script got stuck at chromosome 17 both times. I have examined the STAR alignment statistics, and chromosome 17 does not seem to have abnormally large number of reads. 

I understand the question is not specific so I am not looking for a direct answer from you. Rather, what debugging steps would you suggest? 

Thanks, 
Bosh

**Comment by gmcvicker** [comment]
I think that this was related to high recursion depth in regions with a very high density of SNPs. This should now be solved with new version of mapping pipeline (WASP release v0.2)
