### ISSUE TITLE
Filtering based on MAPQ after WASP

### ISSUE THREAD

**Issue by antozito** [bmvdgeijn/WASP#43]
Hi all, 

I implemented WASP to reduce mapping biases and reference biases. 
My question is: Is it still recommended to implement an additional filtering step based on MAPQ 10 or 20 of reads  after WASP's pipeline or this will cause an underestimation of read counting and excessive reads loss ? In am wondering if the additional filtering I implemented is causing loss of power to detect true expression data.

Best
anto
kings College London

**Comment by gmcvicker** [comment]
Hi Anto,

My opinion is that filtering on MAPQ10 or MAPQ20 should be fine and should not result in the loss of an excessive number of reads. 

One caveat is that the mapping quality of a read could potentially differ depending on what allele is present in a read. Therefore, to avoid bias I would recommend doing the MAPQ filtering as part of both the initial mapping (Step 1) and remapping (Step 3) steps of the pipeline. 

Hope this helps,

Graham

**Comment by antozito** [comment]
Hi Graham, 

many thanks. I have done as you recommended, providing as additionally filtering for properly paired
reads. 
Thanks, 
antonino
