### ISSUE TITLE
unaligned reads are not properly handled NOW?

### ISSUE THREAD

**Issue by walterSG** [bmvdgeijn/WASP#49]
Dear Bryce and Graham,

I have recently updated WASP to the last version, but I have come across some brand new issues with unmapped reads (those that contain '*' on the Reference field at the end of the sorted bam file) in the find_intersecting_snps.py script. This didn't happen with my last WASP version.

In particular, the getrname method (also deprecated) at line 582:

cur_chrom = files.input_bam.getrname(read.tid)

is returning -1, so it is crashing at the end because it is out of the 'tid' range. In a future, will it be possible again for find_intersecting_snps.py to handle this reads without need to previously filtering them out? Or am I missing something here?

Many thanks,
Walter

**Comment by gmcvicker** [comment]
Hi Walter,
Thanks for letting us know about this new problem.  It should not be hard to fix this. I will do so and let you know once the fix is committed.
Thanks,
Graham

**Comment by gmcvicker** [comment]
Hi Walter,
I have committed a fix for this to the master and development branches:
https://github.com/bmvdgeijn/WASP/commit/6274f098248f4fa21406bd1389c97f542626ea9f

Please pull the change and try it out. If you run into any further problems please let us know.

Thank you,
Graham

**Comment by sciguy** [comment]
Hi Graham,

I believe I'm having the same issue. I'm using the latest version of WASP (422ef94). Reads that contain an '*' in the RNEXT field crash find_intersecting_snps.py. If I remove reads with a mate unmapped flag, then find_intersecting_snps.py works. The error I get when the program crashes can be found below.

Thank you,
Jason

Traceback (most recent call last):
  File "WASP/mapping/find_intersecting_snps.py", line 947, in <module>
    samples=samples)
  File "WASP/mapping/find_intersecting_snps.py", line 923, in main
    samples=samples)
  File "WASP/mapping/find_intersecting_snps.py", line 635, in filter_reads
    if read.next_reference_name is None:
  File "pysam/calignedsegment.pyx", line 941, in pysam.calignedsegment.AlignedSegment.next_reference_name.__get__ (pysam/calignedsegment.c:11814)
  File "pysam/calignmentfile.pyx", line 1653, in pysam.calignmentfile.AlignmentFile.getrname (pysam/calignmentfile.c:16998)
  File "pysam/calignmentfile.pyx", line 678, in pysam.calignmentfile.AlignmentFile.get_reference_name (pysam/calignmentfile.c:8350)
ValueError: reference_id -1 out of range 0<=tid<4584

**Comment by gmcvicker** [comment]
Hi Jason,
I think that i have fixed your problem by making the code check the mate unmapped flag instead of the mate reference name. I have committed a change here (https://github.com/bmvdgeijn/WASP/commit/f6e1d55fde394a6fef41024c6321372aa1170b36). Please let us know if you run into any other issues or if this doesn't appear to fix your issue.

Thank you,
Graham

**Comment by sciguy** [comment]
Hi Graham,

It works. Thanks for the quick response.

Cheers,
Jason
