### ISSUE TITLE
Paired end reads are not supported in rmdup.py

### ISSUE THREAD

**Issue by adriaan-vd-graaf** [bmvdgeijn/WASP#5]
Dear Sir,

The script rmdup.py only supports single end reads, while this is not stated anywhere. It may nice to have this functionality implemented, or at least a warning about this in the documentation.

Thank you for your time, 
Adriaan

**Comment by machadoheather** [comment]
I would also be interested in rmdup.py functionality for paired end reads. Is that in the works, by any chance?

Best,
Heather

**Comment by bmvdgeijn** [comment]
Hi Adriaan and Heather,

We will work on adding that functionality in now.  Our apologies for the
delay, we have been swamped by revisions.

**Comment by bmvdgeijn** [comment]
We added a script for paired end rmdup.  It currently assumes that the
pairs can be matched based on query name (the first column of the bam
files) and that the input is sorted.

**Comment by machadoheather** [comment]
Wonderful, thank you!

Best,
Heather

On Wed, Jul 1, 2015 at 3:22 PM, Bryce van de Geijn <notifications@github.com
