### ISSUE TITLE
Okay to include PEER covariants? 

### ISSUE THREAD

**Issue by boxiangliu** [bmvdgeijn/WASP#55]
Hi Graham,

The final combined_test.py can take principle components into account. Would it be okay to use PEER factors, age, gender and other covariates? 

Bosh

**Comment by gmcvicker** [comment]
In principle this should work, but I have not tried this myself. I have also not tested the PC option of the CHT for a long time, so let us know if you try this and run into any problems.

**Comment by bmvdgeijn** [comment]
Since the coefficients are fit one at a time, it would likely work better
if the covariates are orthogonal (as PCs are ).  I might suggest
orthogonalizing the covariate matrix (perhaps using PCA).
