### ISSUE TITLE
cross-ref CHT output to peaks

### ISSUE THREAD

**Issue by sashagusev** [bmvdgeijn/WASP#56]
Thanks for putting together such a detailed pipeline description, it was really helpful in getting everything working.

I ran the CHT using SNPs that were inside and proximal to ChIP-seq peaks (I assume the haplotypes of heterozygous carriers of proximal SNPs are tested for imbalance). This means some SNPs get tested twice for multiple peaks. However, the CHT output only lists the test SNP position and not the target peak that it was tested for. Am I screwing something up by testing proximal SNPs? Is there a way to connect the CHT output back to the corresponding peak positions?

**Comment by bmvdgeijn** [comment]
Using proximal SNPs as test SNPs is fine as long as the SNPs are close
enough that the haplotypes are accurate. The input files for the CHT
include the target coordinates and the output should be in that same
order.  It might be easiest for now to match lines.
