### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by Anne-oxford** [bmvdgeijn/WASP#57]
Hi Graham,

I'm trying to run the find_intersecting_snps.py script but it reserves unto 50G of memory for one BAM. Is this normal? Also the --samples are those the samples in my bam file or samples in the 1000G file used to create the SNP files?

**Comment by gmcvicker** [comment]
Hi Anne,

The --samples specify the identifiers of that samples that you are using in the haplotypes.h5 file. E.g. if you made a haplotypes file containing all of the 1000 genomes samples, but are only using 20 of these individuals in your study, you would provide a list of identifiers for the 20.

Each BAM file should only contain reads for a single individual (but polymorphic SNPs for all individuals in your study are considered when filtering reads).

It is not normal for the script to use 50GB of memory. How many samples are you using, and how large is your BAM file?

**Comment by Anne-oxford** [comment]
Hi Graham,

Thanks for getting back to me.

I think I might have misunderstood the pipeline. I assumed the haplotypes file was generated using a reference population and so I used the 1000 genomes, not my own samples.

Regards,
Anne

**Comment by Anne-oxford** [comment]
Hi Graham,

Thanks for your help. The script works fine for me now.
