### ISSUE TITLE
saw read more times than expected

### ISSUE THREAD

**Issue by sashagusev** [bmvdgeijn/WASP#60]
Hey guys, I'm going through the remapping pipeline and getting the following error

>  "ValueError: saw read SEQCORE-1829592:151:C7NHAANXX:8:2108:19771:96214 more times than expected in input file"

after running `filter_remapped_reads.py`. The steps I took were as follows:

```
# identify intersecting SNPs in MAP1
python $WASP_DIR/mapping/find_intersecting_snps.py \
--is_sorted \
--output_dir ./ \
--snp_tab $PRE.snp_tab.h5 \
--snp_index $PRE.snp_index.h5 \
--haplotype $PRE.haps.h5 \
--samples $INP.IND \
$INP.MAP1.bam

# remap using bowtie to generate MAP2
zcat $INP.MAP1.remap.fq.gz | bowtie2 -p 16 -x hg19 - -S $INP.MAP2.sam
samtools view -bS $INP.MAP2.sam | samtools sort -o $INP.MAP2.bam -
samtools index $INP.MAP2.bam

# run the filter on MAP1 and MAP2 to generate MAP2.keep
python $WASP_DIR/mapping/filter_remapped_reads.py \
$INP.MAP1.to.remap.bam \
$INP.MAP2.bam \
$INP.MAP2.keep.bam
```

When I look for this read in the remapped output it does show up twice:

```
$ grep SEQCORE-1829592:151:C7NHAANXX:8:2108:19771:96214 $INP.MAP2.sam
SEQCORE-1829592:151:C7NHAANXX:8:2108:19771:96214.29680282.1.1	0	chr16	29680282	42	126M	*	0	0	AACATAGAAAGACCCTGTCTCTACAAAAACACAAAAAATTAGCCAGGCGTGGTGGTGCATGCCTGTAGTACCAGCTACTTGAGAAGCAGAGGCAGGAGGACTGCTTGAAGCCAGGAGTTTGAGACC	FFFFFFFF<<///<FFFB/FFFB<FF<FFFFFFFF/BF<FFFFFFFFFB/FFFFFFFFFBF/FFB/FF<<//BFFFBFFFFBBBFB//F<BFBFFFF<FFFFF/<FBFF/</BBFBFFFFFBBB/B	AS:i:-3	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:87T38	YT:Z:UU
SEQCORE-1829592:151:C7NHAANXX:8:2108:19771:96214.29680187.1.1	0	chr16	29680187	42	126M	*	0	0	GATCCAGCGCAGTGGCTCATGCCTGTAATCCCAGCACTTTGGGAGGCAGAGCAGGGAGGATTGCTTGAGTCTAGGAGTTCAAGACCAGCCTGGGTAACATAGAAAGACCCTGTCTCTACAAAAACA	BBBBB/BFFFFFFFBFFFFFFF<FFFFFFFFFFF</FFFFFFFFFF/FBFFBBFFFFFFBFFFFFBF<F//FBFFFF</BFFB<FBFF/F<FBFBFFFBFFFFFFFFFFFFBFBFFFFFFFFBB/B	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:126	YT:Z:UU
```

any idea what I'm doing wrong or should try to diagnose it? Appreciate any suggestions.

**Comment by bmvdgeijn** [comment]
Hi Sasha,

Though the same name appears multiple times, it looks like there are
different sequences associated with the 2 reads.  Can you check the fastq
for 2 instances of SEQCORE-1829592:151:C7NHAANXX:8:2108:19771:96214?

Bryce

**Comment by sashagusev** [comment]
Hey Bryce, yes this QNAME shows up four times in the $INP.MAP1.remap.qf.gz:

```
@SEQCORE-1829592:151:C7NHAANXX:8:2108:19771:96214.29680187.1.1
GATCCAGCGCAGTGGCTCATGCCTGTAATCCCAGCACTTTGGGAGGCAGAGCAGGGAGGATTGCTTGAGTCTAGGAGTTCAAGACCAGCCTGGGTAACATAGAAAGACCCTGTCTCTACAAAAACA
+SEQCORE-1829592:151:C7NHAANXX:8:2108:19771:96214.29680187.1.1
BBBBB/BFFFFFFFBFFFFFFF<FFFFFFFFFFF</FFFFFFFFFF/FBFFBBFFFFFFBFFFFFBF<F//FBFFFF</BFFB<FBFF/F<FBFBFFFBFFFFFFFFFFFFBFBFFFFFFFFBB/B
@SEQCORE-1829592:151:C7NHAANXX:8:2108:19771:96214.29680282.1.1
AACATAGAAAGACCCTGTCTCTACAAAAACACAAAAAATTAGCCAGGCGTGGTGGTGCATGCCTGTAGTACCAGCTACTTGAGAAGCAGAGGCAGGAGGACTGCTTGAAGCCAGGAGTTTGAGACC
+SEQCORE-1829592:151:C7NHAANXX:8:2108:19771:96214.29680282.1.1
FFFFFFFF<<///<FFFB/FFFB<FF<FFFFFFFF/BF<FFFFFFFFFB/FFFFFFFFFBF/FFB/FF<<//BFFFBFFFFBBBFB//F<BFBFFFF<FFFFF/<FBFF/</BBFBFFFFFBBB/B
```

and it shows up twice in the original fastq data (this is single-end ATAC-seq):
```
@SEQCORE-1829592:151:C7NHAANXX:8:2108:19771:96214
GGTCTCAAACTCCTGGCTGCAAGCAGTCCTCCTGCCTCTGCTTCTCAAGTAGCTGGTACTACAGGCATGCACCACCACGCCTGGCTAATTTTTTGTGTTTTTGTAGAGACAGGGTCTTTCTATGTT
@SEQCORE-1829592:151:C7NHAANXX:8:2108:19771:96214
GATCCAGCGCAGTGGCTCATGCCTGTAATCCCAGCACTTTGGGAGGCAGAGCAGGGAGGATTGCTTGAGGCTAGGAGTTCAAGACCAGCCTGGGTAACATAGAAAGACCCTGTCTCTACAAAAACA
```

**Comment by bmvdgeijn** [comment]
Hi Sasha,

As far as I know QNAMEs are supposed to be unique identifiers given by the
sequencer that describe the run and physical position of the read on the
flow cell.  There should not be duplicates.  Perhaps the two dots were
located very close together and ended up with the same position?  It is a
bit fishy that they mapped to similar genomic locations, but I would just
throw both reads out.

Hope that helps,
Bryce

**Comment by bmvdgeijn** [comment]
If I had to guess, I would say a single fragment split while bound to the
flowcell and led to two reads that were both physically and genomically
close together.  They probably aren't independent and at least one should
be tossed.

**Comment by sashagusev** [comment]
Okay, thanks for the quick reply. I'm looking now and nearly every read has a duplicate QNAME, so I'll try to go back to the folks who generated this and figure it out.

**Comment by bmvdgeijn** [comment]
That sounds like it is paired end data.

**Comment by sashagusev** [comment]
good call! Turns out it was paired end data, but with the end information stripped out and reads treated as independent

**Comment by haibol2016** [comment]
how to handle this type issue? I have the sample problem.

**Comment by sashagusev** [comment]
In my case, I added suffixes to QNAMES to make them independent and then treated the input as single-end reads.
