### ISSUE TITLE
reads with flipped alleles

### ISSUE THREAD

**Issue by KeyingLu** [bmvdgeijn/WASP#64]
Hi,
I have read some information that flipped alleles denote A/T or G/C SNPs, but I don't know why only these reads need to remap. Could you please give me illustration more clearly?

Thank you very much!

**Comment by bmvdgeijn** [comment]
Hi Keying,

I am not sure that I completely understand this question.  If you have an
A/T SNP, you only have to simulate reads with the A and T alleles since G
and C are presumably not occurring in your sample.

Does this help?  Perhaps you could restate your question.
Bryce
