### ISSUE TITLE
Failed to parse genotype likelihoods

### ISSUE THREAD

**Issue by Liying1996** [bmvdgeijn/WASP#66]
Hi,

When I do this step:
./snp2h5/snp2h5 --chrom data/ucsc/hg19/chromInfo.txt.gz \
        --format vcf \
        --geno_prob geno_probs.h5 \
        1000G/supporting/genotype_likelihoods/shapeit2/ALL.chr*.gl.vcf.gz

An error occurres:
ERROR: vcf.c:311: failed to parse genotype likelihoods from string '0,-2.96423' (line: 90250)

This error occurs on the chromosome X (and Y),  the GLs of some SNPs in male samples are only two figures(such as '0,-2.96423'). May I ask how do you solve this problem? Can I delete this data?

Thank you so much!

**Comment by gmcvicker** [comment]
This clearly a bug in parsing chrX and chrY genotype likelihoods from VCF files. I will look into this. I would recommend skipping these chromosomes for now (you can delete or move the chrX and chrY files).

**Comment by Liying1996** [comment]
Hi!

Much thanks for your reply! Meanwhile, we have an another problem:
when  we use the VCF files and separate VCF files that contain genotype likelihoods (GL) to create h5 files,  we found that SNPs in the two kind of files are not exactly the same. For example,   the chr22 genotype VCF file contains 1103547 SNPs; but the separate VCF file of chr22 that contain genotype likelihoods (GL) only contains 1056205 SNPs. This will affect the next steps. 
Can I delete the different SNPs to make them same? Or what should I do?

genotype VCF files: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp//release/20130502/
GL files: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp//release/20130502/supporting/genotype_likelihoods/shapeit2/

Thank you very much !

**Comment by rwomersley** [comment]
Hi there! 

I wondered if anybody else was having similar issues with other chromosomes? When generating the genotype probability alone for chr*.gl.vcf.gz files from 1000G data, snp2h5 gives the error 
"ERROR: vcf.c:376: failed to parse genotype likelihoods from string '-5,-0.742998' (line: 7094)"
for chr 1. Similar but a slightly different "vcf.c:" number to the previous comment. I have tried this with other chromosomes and get the same error unfortunately.

The full read out is;
```

> chromosome: chr1, length: 248956422bp
> reading from file ./1000G/supporting/ALL.chr1.phase3_bc_union.20130502.biallelic_svm_snps_indelsAF0.005_svs.gl.vcf.gz
> counting lines in file
>   total lines: 7093
> reading VCF header
>   VCF header lines: 5
>   number of samples: 2535
> initializing HDF5 matrix with dimension: (7088, 7605)
> parsing file and writing to HDF5 files
> ERROR: vcf.c:376: failed to parse genotype likelihoods from string '-5,-0.742998' (line: 7094)

```

The line it fails on is always one number after the total lines in the file. 

The WASP version is also the most recent one. 

Thank you so much in advance for any help!
