### ISSUE TITLE
ind_intersecting_snps.py error

### ISSUE THREAD

**Issue by raungar** [bmvdgeijn/WASP#79]
I'm getting the following error
<img width="911" alt="screen shot 2018-11-27 at 1 15 39 pm" src="https://user-images.githubusercontent.com/18176863/49403726-57cf5180-f702-11e8-81aa-b147c0f8651d.png">

I know that snp_tab.h5 definitely exists and is not empty (there are >1000 lines), and I reran the code that creates this file  and I still get this error. I also redownloaded WASP to see if there was an error in my local installation but got the same result.

my code is below

``` 
$WASPdir/snp2h5/snp2h5 --chrom "$dir/$chrom_file" \
         --format vcf \
         --haplotype haplotype.h5 \
         --snp_index snp_index.h5 \
         --snp_tab snp_tab.h5 \
         $vcfs_dir/chr*.vcf.gz


first=`head -1 mkk.headers.txt | awk '{print $1}'`

 python $WASPdir/mapping/find_intersecting_snps.py \
          --is_paired_end \
          --is_sorted \
          --output_dir find_intersecting_snps \
          --snp_tab snp_tab.h5 \
          --snp_index snp_index.h5 \
          --haplotype haplotype.h5 \
          --samples mkk.headers.txt \
          $bams_dir/$first/Aligned.sortedByCoord.out.bam 
```

I would appreciate insights into what might be going on.

**Comment by gmcvicker** [comment]
I am not sure what is causing this issue. If you are using the latest version of WASP then you should be using python 3, however, it looks like you are using python 2.7.  Can you try running find_intersecting_snps.py again but with python 3? I am not sure how this would cause the problem you are experiencing, but it is worth trying.  

If that doesn't work, I can try to take a look at the files to see if I can reproduce the problem. This would be easiest if you made a very short test VCF (e.g. 1000 lines) and then re-created the HDF5 files.

**Comment by raungar** [comment]
Thank you for your help. I tried updating to python3 and that did not work. What I ended up figuring out was that my chrom_info.txt was not correct, and this was the error that was thrown because of it.
