### ISSUE TITLE
Mapping Step 2 

### ISSUE THREAD

**Issue by olneykimberly** [bmvdgeijn/WASP#8]
The output files are empty but I receive no error message or anything. I have no idea why my accepted_hits.quality.remap.num.gz and remap.fq.gz files are empty

**Comment by bmvdgeijn** [comment]
What is written to stdout and stderr?  There might not be an error, but
this could still give us some clues.

**Comment by olneykimberly** [comment]
Thank you so much for getting back to me, I greatly appreciate your help! I can not seem to find stderr anywhere. I’ve looked everywhere. Am I supposed to pull it out with a command in terminal because the file doesn’t seem to exist on my computer. 

I’m sorry I’m not very helpful in resolving the issue. I’m new to this :/

Thank you so much!

**Comment by bmvdgeijn** [comment]
Ah sorry for the confusion.  Earlier you sent me what was printed when you
ran the second step, but there was an error.  I would like what was printed
when there wasn't an error.  For example, "Starting chr1"....

**Comment by olneykimberly** [comment]
I didn’t save it but I didn’t receive an error messages after running step 2 on Mapping and even said Finished! when it was done.

My command $ python /Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/ASE_WASP_Files/find_intersecting_snps.py /Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/NA06894_tophat_out/accepted_hits.bam /Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/ASE_WASP_Files/1000GenomesData/SNP_files
Starting on chr1
starting on chr10
It did this for each chr#
chrX
chrY
Finished!

However my new files to remap are empty

**Comment by bmvdgeijn** [comment]
That is strange.  Have you checked to make sure that the SNP files you sent
it aren't empty?  There should also be a *.keep.bam file which contains
reads that don't overlap SNPs.  Is it empty as well?

**Comment by olneykimberly** [comment]
My SNP files are filled and are done correctly with position, ref allele, alt allele each file is ~ 3-20MB and the accepted_hits.keep.bam is 7.7MB

**Comment by olneykimberly** [comment]
Do the chr#.snps.txt.gz files need to contain a header? "position RefAllele AltAllele" because my chr# files do not contain a header.

**Comment by bmvdgeijn** [comment]
They shouldn't contain headers.  How large was your originally mapped bam?

**Comment by olneykimberly** [comment]
My original mapped bam from running TopHat is 25.7MB

**Comment by bmvdgeijn** [comment]
That is unsorted?  The sorted bam files often end up smaller.  Are you SNPs
sorted?

**Comment by olneykimberly** [comment]
I’m sorry I don’t fully understand 
accepted_hits.sort.bam 25.7MB
accepted_hits.bam 25.7MB 

and I don’t know if my SNPs are sorted or not. 

I’m confused. 

Here is my TopHat command $ ./tophat --no-coverage-search -o /Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/NA06894_tophat_out -p 6 -G /Users/olneykimberly/Desktop/1_code/gencode.v18.annotation.gtf /Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/ASE_WASP_Files/1000GenomesData/GenomicReference/build37_used_by_cg /Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/ASE_WASP_Files/1000GenomesData/SRR_files/SRR035022.filt.fastq 

Output files from TopHat:

**Comment by bmvdgeijn** [comment]
I'm trying to get a sense of how many reads are kept after step 2.  It
looks like it's only ~1/4.  If the SNPs aren't sorted then the script
breaks down, but I believe there should be a warning message.  Since the
files are pretty small, do you mind sending me accepted_hits.bam file and
the SNP files you are using?  It might be faster if I take a look at them.

**Comment by olneykimberly** [comment]
Attachments available until May 6, 2015
Absolutely! Thank you again for helping me :)

Here is my accepted_hits.bam. The SNP files are too large to send over all of them so I selected chr13 to send since it’s one of the smaller chromosomes. If you need all of them I’d be happy to send them over I’ll just have to send multiple emails if that’s okay. 

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fs3-us-ore-108-prod.digitalhub.com%2FB%2FAbqlPCv26oQCcKCINwVC3qauaKYdAUGN7IL0W-8D4scxYlKWzm_cQXym%2F%24%7Bf%7D%3Fo%3DApvqOcNn3B5gPjvI-fiaRDiUkc8hS0mt8sORBJ__gNaS%26v%3D1%26x%3D3%26a%3DBQS6Kf_Kboj_A57jKgEA_wHIAP8eR8AA%26e%3D1430950890%26k%3D%24%7Buk%7D%26r%3D0A1C395C-E349-48E7-B99F-1906B89E2631-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DBAA989C0-BC7C-4E78-B147-B1DA248F6742%26z%3Dhttps%253A%252F%252Fp21-content.icloud.com%253A443%26s%3DxpTeI5b8SVtb64O0iTbR0msRgj8&uk=GytMDZ9eT1F_d7VKCuZTcQ&f=accepted_hits.bam&sz=25691867>accepted_hits.bam
25.7 MB

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fs3-us-ore-108-prod.digitalhub.com%2FB%2FAR7EzD_NUVVYWpNuutUqWajbcsJKAVQz2G8SPUXPbw-gF7yPHQN-KfZ0%2F%24%7Bf%7D%3Fo%3DAgpe1BfbfECEghNWP2mRGe8T67N-HKRs21HKBmLAC7Yk%26v%3D1%26x%3D3%26a%3DBbTHZwJoDZ8EA57jKgEA_wHIAP8q07vU%26e%3D1430950891%26k%3D%24%7Buk%7D%26r%3DAB33538D-541D-4A10-ABF9-051AD92EB2FC-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DBAA989C0-BC7C-4E78-B147-B1DA248F6742%26z%3Dhttps%253A%252F%252Fp21-content.icloud.com%253A443%26s%3Dx8jRpbd0xoRxUACD1vN6pzsrxmo&uk=pEqaG4NBH8Cpt1SniqBoQw&f=chr13.snps.txt.gz&sz=7050476>chr13.snps.txt.gz
7.1 MB

**Comment by olneykimberly** [comment]
Did you get my data I sent over?
