### ISSUE TITLE
speedup for fit_as_coefficients?

### ISSUE THREAD

**Issue by lw157** [bmvdgeijn/WASP#97]
Hi Graham/Bryce,
The fit_as_coefficients has been running for 5 days.  From the "std" print out, it  was about 3 days to process one sample, but I have about 50 samples, so it will take 150 days? 

Can I run each sample separately? Or should I skip some loci, such as skip option for fit_bnb_coefficients?

Do you have any other suggestion that could speedup this step? Thanks a lot.
Best,
Liuyang

**Comment by bmvdgeijn** [comment]
Hi Liuyang,

I believe this is another case where skipping many of the loci will be your best bet.  You don’t need 2 million loci to estimate one parameter.

Bryce

**Comment by lw157** [comment]
> Hi Liuyang, I believe this is another case where skipping many of the loci will be your best bet. You don’t need 2 million loci to estimate one parameter. Bryce
> […](#)
> Sent from my iPhone
> On Jun 8, 2020, at 9:54 AM, Liuyang Wang ***@***.***> wrote: ﻿ Hi Graham, The fit_as_coefficients has been running for 5 days. From the "std" print out, it was about 3 days to process one sample, but I have about 50 samples, so it will take 150 days? Can I run each sample separately? Or should I skip some loci, such as skip option for fit_bnb_coefficients? Do you have any other suggestion that could speedup this step? Thanks a lot. Best, Liuyang — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi Bryce,
    I will add the skip option to this function. Thanks for your suggestions. Cool.
Best,
Liuyang
